# -*- coding: utf-8 -*-
"""iris classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lkN1-AHF3dc0Zor1rdBmDuJ7UWevDFx

Mount drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""Import Necessary Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

"""Load the Dataset"""

file_path = '/content/drive/MyDrive/codsoft dataset/IRIS.csv'
df = pd.read_csv(file_path)


print(df.head())

"""Exploratory Data Analysis (EDA)

"""

print(df.describe())
print(df.isnull().sum())

"""Data Visualization"""

sns.pairplot(df, hue='species')
plt.show()

df.hist(bins=20, figsize=(10, 10))
plt.show()

"""Data Preprocessing"""

df['species'] = df['species'].astype('category').cat.codes
X = df.drop('species', axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Feature Scaling"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""Building and Training the Model"""

model = LogisticRegression()
model.fit(X_train, y_train)

"""Evaluating the Model"""

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))